### ISSUE TITLE
[BUG] Players without any destroy/bypass/open permissons could open the chest shop owned by another player

### ISSUE THREAD

**Issue by Terry-mcgit** [QuickShop-Community/QuickShop-Hikari#1709]
### Description

When a player in my server without any destroy/bypass/open permissons right-clicked the chest shop owned by another player, the player opened the chest!
I'm sure that I didn't give the player any destroy/bypass/open permissons. I'm using LuckPerms for permissions.

### Steps to reproduce

1.Create a shop
2.Let a player right-click it
3.The player open the chest!

### Expected Behaviour

QuickShop-Hikari should block the chest when player is right-clicking it.

### Screenshots

![图片](https://github.com/user-attachments/assets/cfceef7a-9c3d-455e-ba1f-09117e580dc5)

### `/quickshop paste` URL

https://ghost-chu.github.io/quickshop-hikari-paste-viewer/?remote=https%3A%2F%2Fbytebin.lucko.me%2FkcOM4mAor7

### Checklist

- [X] I'm running Paper or Spigot, and not a fork
- [X] I confirm that Paper/Spigot has been updated to the latest build
- [X] I confirm that QuickShop-Hikari has been updated to the latest stable version released on Modrinth (or the latest CI version)
- [ ] I confirm that I have not read these checkboxes and therefore I just ticked them all.
- [X] I confirm that I'm using QuickShop-Hikari, not QuickShop-Reremake, and I'm well aware that they're maintained by different people, and that Reremake issues shouldn't be reported here.
- [X] I confirm that I am running a server that is not a Hybird Server, (e.g. Mohist, Magma, CatServer, Banner, etc.), and I am aware that QuickShop-Hikari may not function properly on a Forge/Fabric hybrid server, and I am running at my own risk on such a server program, and I am aware that the I run such server-side programs at my own risk and know that I will not receive any support or help for this behavior.
- [X] I am well aware that if the Issue Ticket is not filled out correctly and completely, it will simply be closed without any response or reason.

**Comment by YuanYuanOwO** [comment]
`quickshop.player` is the only permission you should give players

**Comment by YuanYuanOwO** [comment]
#1708

**Comment by Terry-mcgit** [comment]
i just give `quickshop.player` to my players,but it doesn't works

**Comment by YuanYuanOwO** [comment]
> i just give `quickshop.player` to my players,but it doesn't works

move to #1708

**Comment by Terry-mcgit** [comment]
thank u, and i'm a staff of zirran's server.
