### ISSUE TITLE
[BUG] Virtual drop item display is not visible on the Bedrock Edition.

### ISSUE THREAD

**Issue by chenshupe** [QuickShop-Community/QuickShop-Hikari#1753]
### Description

Dear developer, hello. In the cross-platform server using the Geyser plugin, when the display-type parameter is set to 2 (Virtual Item), the floating item display for the chest shop can be seen normally by Java Edition players, but Bedrock Edition players cannot see it. If using Normal Dropped Item, it is possible to infinitely duplicate items with water flow. I don't know if you can fix this issue. Thank you for your efforts.

Here is the translation for your reference. If you need further assistance or have more specific questions, feel free to let me know.

### Steps to reproduce

1.Create a store profile and select the mode
2.Players in the Bedrock Edition cannot see virtual floating objects.

### Expected Behaviour

Hope the developers can fix this issue.

### Screenshots

![846AE6E4634ABD887890114A0751D7DB](https://github.com/user-attachments/assets/b13d1ba3-24f0-44c2-9f62-373954e71360)
![E4713834C9A4D4288F2AD98F75D3BC5C](https://github.com/user-attachments/assets/ddac8265-802e-4102-83b3-274776cc71ce)

### `/quickshop paste` URL

https://ghost-chu.github.io/quickshop-hikari-paste-viewer/?remote=https%3A%2F%2Fbytebin.lucko.me%2FI5KIn2GOt7

### Checklist

- [X] I'm running Paper or Spigot, and not a fork
- [X] I confirm that Paper/Spigot has been updated to the latest build
- [X] I confirm that QuickShop-Hikari has been updated to the latest stable version released on Modrinth (or the latest CI version)
- [ ] I confirm that I have not read these checkboxes and therefore I just ticked them all.
- [X] I confirm that I'm using QuickShop-Hikari, not QuickShop-Reremake, and I'm well aware that they're maintained by different people, and that Reremake issues shouldn't be reported here.
- [X] I confirm that I am running a server that is not a Hybird Server, (e.g. Mohist, Magma, CatServer, Banner, etc.), and I am aware that QuickShop-Hikari may not function properly on a Forge/Fabric hybrid server, and I am running at my own risk on such a server program, and I am aware that the I run such server-side programs at my own risk and know that I will not receive any support or help for this behavior.
- [ ] I am well aware that if the Issue Ticket is not filled out correctly and completely, it will simply be closed without any response or reason.

**Comment by chenshupe** [comment]
Thank you. It's my fault. I didn't realize there was an addon plugin.



---Original---
From: ***@***.***&gt;
Date: Tue, Aug 27, 2024 16:01 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [QuickShop-Community/QuickShop-Hikari] [BUG] Virtual drop itemdisplay is not visible on the Bedrock Edition. (Issue #1753)




 
https://quickshop-community.github.io/QuickShop-Hikari-Documents/docs/addon/displaycontrol

**Comment by chenshupe** [comment]
Hello, my friend. I installed the displaycontrol plug-in according to the document, but it failed to make its bedrock version display virtual items. I also installed bungeecord and its geyser version, but it failed to load successfully.



---Original---
From: ***@***.***&gt;
Date: Tue, Aug 27, 2024 16:01 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [QuickShop-Community/QuickShop-Hikari] [BUG] Virtual drop itemdisplay is not visible on the Bedrock Edition. (Issue #1753)




 
https://quickshop-community.github.io/QuickShop-Hikari-Documents/docs/addon/displaycontrol

**Comment by YuanYuanOwO** [comment]
> Hello, my friend. I installed the displaycontrol plug-in according to the document, but it failed to make its bedrock version display virtual items. I also installed bungeecord and its geyser version, but it failed to load successfully.
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Tue, Aug 27, 2024 16:01 PM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [QuickShop-Community/QuickShop-Hikari] [BUG] Virtual drop itemdisplay is not visible on the Bedrock Edition. (Issue #1753) https://quickshop-community.github.io/QuickShop-Hikari-Documents/docs/addon/displaycontrol — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

我觉得应该基岩版无法显示悬浮物是正常情况，以及，当插件无法加载时，您应该上传错误日志。  


I think it is normal that the bedrock version should not be able to display the hover, as well as, you should upload an error log when the plugin fails to load.

**Comment by chenshupe** [comment]
我嘞个豆 大佬你是中国人啊 可能是间歇泉的问题吧&nbsp; Java能看到基岩版看不到&nbsp;&nbsp;



---Original---
From: ***@***.***&gt;
Date: Tue, Aug 27, 2024 22:09 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [QuickShop-Community/QuickShop-Hikari] [BUG] Virtual drop itemdisplay is not visible on the Bedrock Edition. (Issue #1753)




  
Hello, my friend. I installed the displaycontrol plug-in according to the document, but it failed to make its bedrock version display virtual items. I also installed bungeecord and its geyser version, but it failed to load successfully.
 …
 ---Original--- From: @.&gt; Date: Tue, Aug 27, 2024 16:01 PM To: @.&gt;; Cc: @.@.&gt;; Subject: Re: [QuickShop-Community/QuickShop-Hikari] [BUG] Virtual drop itemdisplay is not visible on the Bedrock Edition. (Issue #1753) https://quickshop-community.github.io/QuickShop-Hikari-Documents/docs/addon/displaycontrol — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
我觉得应该基岩版无法显示悬浮物是正常情况，以及，当插件无法加载时，您应该上传错误日志。
 
I think it is normal that the bedrock version should not be able to display the hover, as well as, you should upload an error log when the plugin fails to load.

**Comment by YuanYuanOwO** [comment]
> 我嘞个豆 大佬你是中国人啊 可能是间歇泉的问题吧&nbsp; Java能看到基岩版看不到&nbsp;&nbsp;
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Tue, Aug 27, 2024 22:09 PM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [QuickShop-Community/QuickShop-Hikari] [BUG] Virtual drop itemdisplay is not visible on the Bedrock Edition. (Issue #1753) Hello, my friend. I installed the displaycontrol plug-in according to the document, but it failed to make its bedrock version display virtual items. I also installed bungeecord and its geyser version, but it failed to load successfully. … ---Original--- From: @.&gt; Date: Tue, Aug 27, 2024 16:01 PM To: @.&gt;; Cc: @.@.&gt;; Subject: Re: [QuickShop-Community/QuickShop-Hikari] [BUG] Virtual drop itemdisplay is not visible on the Bedrock Edition. (Issue #1753) https://quickshop-community.github.io/QuickShop-Hikari-Documents/docs/addon/displaycontrol — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt; 我觉得应该基岩版无法显示悬浮物是正常情况，以及，当插件无法加载时，您应该上传错误日志。 I think it is normal that the bedrock version should not be able to display the hover, as well as, you should upload an error log when the plugin fails to load. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

看文档里的默认行为就是对 Java版客户端 开启悬浮物显示，基岩版客户端 关闭显示  
`Default behavior, will enable display on Java Edition clients, and disable on Bedrock clients.`
我觉得这应该不是一个问题
I think it's not a issue,

**Comment by chenshupe** [comment]
基岩版只能通过真实掉落物来显示了吗&nbsp;



---Original---
From: ***@***.***&gt;
Date: Tue, Aug 27, 2024 22:17 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [QuickShop-Community/QuickShop-Hikari] [BUG] Virtual drop itemdisplay is not visible on the Bedrock Edition. (Issue #1753)




  
我嘞个豆 大佬你是中国人啊 可能是间歇泉的问题吧&nbsp; Java能看到基岩版看不到&nbsp;&nbsp;
 …
 ---Original--- From: @.&gt; Date: Tue, Aug 27, 2024 22:09 PM To: @.&gt;; Cc: @.@.&gt;; Subject: Re: [QuickShop-Community/QuickShop-Hikari] [BUG] Virtual drop itemdisplay is not visible on the Bedrock Edition. (Issue #1753) Hello, my friend. I installed the displaycontrol plug-in according to the document, but it failed to make its bedrock version display virtual items. I also installed bungeecord and its geyser version, but it failed to load successfully. … ---Original--- From: @.&gt; Date: Tue, Aug 27, 2024 16:01 PM To: @.&gt;; Cc: @.@.&gt;; Subject: Re: [QuickShop-Community/QuickShop-Hikari] [BUG] Virtual drop itemdisplay is not visible on the Bedrock Edition. (Issue #1753) https://quickshop-community.github.io/QuickShop-Hikari-Documents/docs/addon/displaycontrol — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt; 我觉得应该基岩版无法显示悬浮物是正常情况，以及，当插件无法加载时，您应该上传错误日志。 I think it is normal that the bedrock version should not be able to display the hover, as well as, you should upload an error log when the plugin fails to load. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt;
  
看文档里的默认行为就是对 Java版客户端 开启悬浮物显示，基岩版客户端 关闭显示
 Default behavior, will enable display on Java Edition clients, and disable on Bedrock clients.
 我觉得这应该不是一个问题
 I think it's not a issue,

**Comment by YuanYuanOwO** [comment]
> 基岩版只能通过真实掉落物来显示了吗&nbsp;
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Tue, Aug 27, 2024 22:17 PM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [QuickShop-Community/QuickShop-Hikari] [BUG] Virtual drop itemdisplay is not visible on the Bedrock Edition. (Issue #1753) 我嘞个豆 大佬你是中国人啊 可能是间歇泉的问题吧&nbsp; Java能看到基岩版看不到&nbsp;&nbsp; … ---Original--- From: @.&gt; Date: Tue, Aug 27, 2024 22:09 PM To: @.&gt;; Cc: @.@.&gt;; Subject: Re: [QuickShop-Community/QuickShop-Hikari] [BUG] Virtual drop itemdisplay is not visible on the Bedrock Edition. (Issue #1753) Hello, my friend. I installed the displaycontrol plug-in according to the document, but it failed to make its bedrock version display virtual items. I also installed bungeecord and its geyser version, but it failed to load successfully. … ---Original--- From: @.&gt; Date: Tue, Aug 27, 2024 16:01 PM To: @.&gt;; Cc: @.@.&gt;; Subject: Re: [QuickShop-Community/QuickShop-Hikari] [BUG] Virtual drop itemdisplay is not visible on the Bedrock Edition. (Issue #1753) https://quickshop-community.github.io/QuickShop-Hikari-Documents/docs/addon/displaycontrol — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt; 我觉得应该基岩版无法显示悬浮物是正常情况，以及，当插件无法加载时，您应该上传错误日志。 I think it is normal that the bedrock version should not be able to display the hover, as well as, you should upload an error log when the plugin fails to load. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt; 看文档里的默认行为就是对 Java版客户端 开启悬浮物显示，基岩版客户端 关闭显示 Default behavior, will enable display on Java Edition clients, and disable on Bedrock clients. 我觉得这应该不是一个问题 I think it's not a issue, — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

建议关闭悬浮物显示，以及你应该上传插件无法加载的错误日志。
真实悬浮物在将来版本中会被移除  
It is recommended to turn off the hover display, as well as you should upload an error log of the plugin not loading.  
Real display-item will be removed in a future version!

**Comment by YuanYuanOwO** [comment]
看起来这不是一个问题，如果您有其它问题请打开一个新的issue，并使用英文（我不是开发者）
It doesn't look like this is a problem, if you have other questions please open a new issue and use English (I'm not a developer)

**Comment by chenshupe** [comment]
Thank you for your patient reply.



---Original---
From: ***@***.***&gt;
Date: Tue, Aug 27, 2024 22:23 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [QuickShop-Community/QuickShop-Hikari] [BUG] Virtual drop itemdisplay is not visible on the Bedrock Edition. (Issue #1753)




 
看起来这不是一个问题，如果您有其它问题请打开一个新的issue，并使用英文（我不是开发者）
 It doesn't look like this is a problem, if you have other questions please open a new issue and use English (I'm not a developer)
